git add caustic_params.py
git add c4_stack.py
git add stack_class_c4.py
git add git_add.sh
git add c4_stack.py
git add c4_clusters.py
git add C4_Richnesses.tab
git add c4_pbs.sh
git add c4_richness.py
git add fits_table.py
git add MassRich/CatPrep.py
git add c4_pairfind.py
